### ISSUE TITLE
Numina installation not working from wheel distribution in mac os x + Py3.6

### ISSUE THREAD

**Issue by gildepaz** [guaix-ucm/numina#153]
Running numina in a fresh new installation (using a different "test" environment) I get the following error:
  File "/Users/agpaz/test/lib/python3.6/site-packages/megaradrp-0.6.dev4-py3.6.egg/megaradrp/recipes/scientific/lcb.py", line 18, in <module>
    from megaradrp.recipes.scientific.base import ImageRecipe
  File "/Users/agpaz/test/lib/python3.6/site-packages/megaradrp-0.6.dev4-py3.6.egg/megaradrp/recipes/scientific/base.py", line 19, in <module>
    import matplotlib.pyplot as plt
  File "/Users/agpaz/test/lib/python3.6/site-packages/matplotlib/pyplot.py", line 116, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/Users/agpaz/test/lib/python3.6/site-packages/matplotlib/backends/__init__.py", line 60, in pylab_setup
    [backend_name], 0)
  File "/Users/agpaz/test/lib/python3.6/site-packages/matplotlib/backends/backend_macosx.py", line 17, in <module>
    from matplotlib.backends import _macosx
RuntimeError: Python is not installed as a framework. The Mac OS X backend will not be able to function correctly if Python is not installed as a framework. See the Python documentation for more information on installing Python as a framework on Mac OS X. Please either reinstall Python as a framework, or try one of the other backends. If you are using (Ana)Conda please install python.app and replace the use of 'python' with 'pythonw'. See 'Working with Matplotlib on OSX' in the Matplotlib FAQ for more information.

**Comment by sergiopasra** [comment]
Relevant for this: https://matplotlib.org/faq/osx_framework.html

**Comment by sergiopasra** [comment]
@gildepaz 

Could you try the following with python3?

```
python -m venv test_wheel2
source test_wheel2/bin/activate
(test_wheel2) $ pip install numina

After this, install a a DRP and try any recipe

**Comment by gildepaz** [comment]
I have tried and I get after the first line:
Error: Command '['/Users/agpaz/test_wheel2/bin/python', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.
I thought I might need to create the environment first with virtualenv so I did:
virtualenv megara_wheel2
This worked and then when I tried again "python -m venv test_wheel2" I get the same error and if I try directly "source test_wheel2/bin/activate" then I get:
bash: test_wheel2/bin/activate: No such file or directory

**Comment by sergiopasra** [comment]
python is python3?

**Comment by gildepaz** [comment]
Yes. "which python" yields "/Users/agpaz/anaconda3/bin/python"

**Comment by gildepaz** [comment]
bash-3.2$ python   
Python 3.6.3 |Anaconda, Inc.| (default, Oct  6 2017, 12:04:38) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by sergiopasra** [comment]
So this is your conda python. Which version is your system python?

**Comment by gildepaz** [comment]
This is a well know issue of matplotlib for OS X (https://matplotlib.org/faq/osx_framework.html). Recommended approach:
- Mac: Conda until "pip install megaradrp". List of Conda packages to be installed will be provided. 
- ManyLinux: "pip install megaradrp" directly.
