### ISSUE TITLE
numina/tools/test_setstate_getstate.py is interpreted as  a test

### ISSUE THREAD

**Issue by sergiopasra** [guaix-ucm/numina#170]
Pytest runs functions with prefix "test_" in modules with name starting with "test_" as tests. 

It's running numina/tools/test_setstate_getstate.py as a test and failing. Could you rename the module so that it doesn't start with "test_"?

**Comment by nicocardiel** [comment]
The function has been renamed as check_setstate_getstate to avoid conflict.
