### ISSUE TITLE
problem installing numina

### ISSUE THREAD

**Issue by amanda-olmo** [guaix-ucm/numina#206]
I am following the instructions to install the development version of numina. I am using Anaconda2, but the environment has python3 as the instructions recommend. The error is copied below.

(megaradev) fis022060:numina root2$ /opt/anaconda2/envs/megaradev/bin/python setup.py build
running build
running build_py
running build_ext
skipping 'src/nirproc.cpp' Cython extension (up-to-date)
skipping 'numina/array/trace/traces.cpp' Cython extension (up-to-date)
skipping 'numina/array/trace/extract.cpp' Cython extension (up-to-date)
skipping 'numina/array/peaks/kernels.c' Cython extension (up-to-date)
skipping 'numina/array/bpm.cpp' Cython extension (up-to-date)
skipping 'numina/array/clippix.c' Cython extension (up-to-date)
building 'numina.array._combine' extension
cc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/opt/anaconda2/envs/megaradev/include -arch x86_64 -I/opt/anaconda2/envs/megaradev/include -arch x86_64 -I/opt/anaconda2/envs/megaradev/lib/python3.7/site-packages/numpy/core/include -I/opt/anaconda2/envs/megaradev/include/python3.7m -c src/combinemodule.cc -o build/temp.macosx-10.7-x86_64-3.7/src/combinemodule.o
warning: include path for stdlibc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead
      [-Wstdlibcxx-not-found]
In file included from src/combinemodule.cc:24:
In file included from /opt/anaconda2/envs/megaradev/lib/python3.7/site-packages/numpy/core/include/numpy/arrayobject.h:4:
In file included from /opt/anaconda2/envs/megaradev/lib/python3.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:12:
In file included from /opt/anaconda2/envs/megaradev/lib/python3.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1832:
/opt/anaconda2/envs/megaradev/lib/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: 
      "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
#warning "Using deprecated NumPy API, disable it with " \
 ^
In file included from src/combinemodule.cc:26:
In file included from src/nu_combine_methods.h:25:
src/nu_combine_defs.h:27:10: fatal error: 'cstddef' file not found
#include <cstddef>
         ^~~~~~~~~
2 warnings and 1 error generated.
error: command 'cc' failed with exit status 1

**Comment by sergiopasra** [comment]
https://numina.readthedocs.io/en/latest/user/install.html#building-ad-installing

Check the note about Mojave

export MACOSX_DEPLOYMENT_TARGET=10.9

**Comment by amanda-olmo** [comment]
Thanks! It solved the problem
