### ISSUE TITLE
numina tools support

### ISSUE THREAD

**Issue by gildepaz** [guaix-ucm/numina#207]
I have noticed that in the numina/tools/ folder there are a number of utilities. Are these stable versions that can be used? Is there a way to call them such as "python -m numina.tools.r6_insert_keyword.py -h"? Thx!

**Comment by nicocardiel** [comment]
In principle they should work properly. For example, you only have to type "numina-r6-insert-keyword" in the command line to execute the utility that inserts/modifies a particular keyword in a FITS header. Try "numina-r6-insert-keyword --help" to access the help info.
