### ISSUE TITLE
Numina not installing in Mac M2

### ISSUE THREAD

**Issue by gildepaz** [guaix-ucm/numina#218]
I am trying to install numina related with the building of the wheel. I get the following error:

      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/agpaz/anaconda3/include -arch arm64 -fPIC -O2 -isystem /Users/agpaz/anaconda3/include -arch arm64 -I/private/var/folders/74/jw2v4xfj6szdmgw56rnlzb040000gn/T/pip-build-env-ja7vcyfm/overlay/lib/python3.10/site-packages/numpy/core/include -I/Users/agpaz/anaconda3/include/python3.10 -c src/numina/array/src/combinemodule.cc -o build/temp.macosx-11.1-arm64-cpython-310/src/numina/array/src/combinemodule.o
      In file included from src/numina/array/src/combinemodule.cc:11:
      In file included from /Users/agpaz/anaconda3/include/python3.10/Python.h:25:
      /Users/agpaz/anaconda3/bin/../include/c++/v1/stdio.h:107:15: fatal error: 'stdio.h' file not found
      #include_next <stdio.h>
                    ^~~~~~~~~
      1 error generated.
      error: command '/Users/agpaz/anaconda3/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for numina
Successfully built pyo2000drp
Failed to build numina
ERROR: Could not build wheels for numina, which is required to install pyproject.toml-based projects

**Comment by sergiopasra** [comment]
Perhaps this helps:

https://stackoverflow.com/questions/71487188/mac-cmake-stdio-h-file-not-found

**Comment by gildepaz** [comment]
That did not work. Finally I had to remove everything related with the pip or python from conda and install the native pip3/python3 from https://www.python.org/downloads/release/python-3123/. That seems to work. Now "pip install -e ../pyo2000drp works.
