### ISSUE TITLE
Enhance travis to check in OSX also

### ISSUE THREAD

**Issue by sergiopasra** [guaix-ucm/numina#26]
Something based in the ci dir in astropy will do the work

**Comment by Pica4x6** [comment]
Issue is still opened: https://github.com/travis-ci/travis-ci/issues/2312

**Comment by sergiopasra** [comment]
Yep, travis lacks Python built-in support in OSX, astropy does the thing more manually, by donwloading Conda, a precompiled Pyhton distribution

[.continuous-integration/travis/setup_environment_osx.sh] (http://github.com/astropy/astropy/blob/master/.continuous-integration/travis/setup_environment_osx.sh)

**Comment by sergiopasra** [comment]
We are not using travis anymore
